# Generated by Django 2.0 on 2019-03-02 16:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account_holder',
            fields=[
                ('acc_no', models.BigIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(10000000000)])),
                ('first_name', models.CharField(blank=True, max_length=25, null=True)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('balance', models.FloatField(blank=True, max_length=50, null=True)),
                ('date_of_opening', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('education', models.CharField(blank=True, choices=[('JD', 'JD'), ('High School', 'High School'), ('Associate', 'Associate'), ('MD', 'MD'), ('Masters', 'Masters'), ('PhD', 'PhD'), ('College', 'College')], max_length=10, null=True)),
                ('occupation', models.CharField(blank=True, choices=[('machine-op-inspct', 'machine-op-inspct'), ('prof-specialty', 'prof-specialty'), ('tech-support', 'tech-support'), ('exec-managerial', 'exec-managerial'), ('sales', 'sales'), ('craft-repair', 'craft-repair'), ('Transport-moving', 'Transport-moving'), ('other-service', 'other-service'), ('priv-house-serv', 'priv-house-serv'), ('armed-forces', 'armed-forces'), ('adm-clerical', 'adm-clerical'), ('protective-serv', 'protective-serv'), ('handlers-cleaners', 'handlers-cleaners'), ('farming-fishing', 'farming-fishing')], max_length=10, null=True)),
                ('capital_gains', models.CharField(blank=True, max_length=10, null=True)),
                ('capital_loss', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_no', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99999999), django.core.validators.MinValueValidator(99999)])),
                ('type', models.CharField(choices=[('Car Insurance', 'Car'), ('Life Insurance', 'Life'), ('Health Insurance', 'Health'), ('Fire Insurance', 'Fire'), ('Travel Insurance', 'Travel')], max_length=20)),
                ('policy_state', models.CharField(choices=[('Maharashtra', 'Maharashtra'), ('Gujarat', 'Gujarat'), ('Karnataka', 'Karnataka')], max_length=20)),
                ('annual_premium', models.IntegerField(blank=True, null=True)),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('incident_type', models.CharField(blank=True, choices=[('Multi-vehicle Collision', 'Multi-vehicle Collision'), ('Single Vehicle Collision', 'Single Vehicle Collision'), ('Vehicle Theft', 'Vehicle Theft'), ('Parked Car', 'Parked Car')], max_length=20, null=True)),
                ('collision_type', models.CharField(blank=True, choices=[('Rear Collision', 'Rear Collision'), ('Side Collision', 'Side Collision'), ('Front Collision', 'Front Collision'), ('Top Collision', '?')], max_length=20, null=True)),
                ('severity', models.CharField(blank=True, choices=[('Minor Damage', 'Minor Damage'), ('Total Loss', 'Total Loss'), ('Major Damage', 'Major Damage'), ('Trivial Damage', 'Trivial Damage')], max_length=20, null=True)),
                ('authorities', models.CharField(blank=True, choices=[('Police', 'Police'), ('Fire', 'Fire'), ('Other', 'Other'), ('Ambulance', 'Ambulance'), ('None', 'None')], max_length=20, null=True)),
                ('state', models.CharField(blank=True, choices=[('Maharashtra', 'Maharashtra'), ('Goa', 'Goa'), ('Karnataka', 'Karnataka'), ('Delhi', 'Delhi'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Bihar', 'Bihar'), ('West Bengal', 'West Bengal')], max_length=20, null=True)),
                ('city', models.CharField(blank=True, choices=[('Mumbai', 'Mumbai'), ('Kolkata', 'Kolkata'), ('Bangalore', 'Bangalore'), ('Patna', 'Patna'), ('Lucknow', 'Lucknow'), ('Amritsar', 'Amritsar')], max_length=20, null=True)),
                ('time', models.TimeField(blank=True, max_length=20, null=True)),
                ('no_of_vehicles', models.IntegerField(blank=True, null=True)),
                ('property_damage', models.CharField(blank=True, choices=[('?', '?'), ('Y', 'YES'), ('N', 'NO')], max_length=20, null=True)),
                ('injuries', models.IntegerField(blank=True, null=True)),
                ('witnesses', models.IntegerField(blank=True, null=True)),
                ('police_report_available', models.IntegerField(blank=True, null=True)),
                ('total_claim', models.FloatField(blank=True, max_length=50, null=True)),
                ('injury_claim', models.FloatField(blank=True, max_length=50, null=True)),
                ('property_claim', models.FloatField(blank=True, max_length=50, null=True)),
                ('vehicle_claim', models.FloatField(blank=True, max_length=50, null=True)),
                ('vehicle_brand', models.CharField(blank=True, choices=[('Suburu', 'Suburu'), ('Dodge', 'Dodge'), ('Saab', 'Saab'), ('Nissan', 'Nissan'), ('Chevrolet', 'Chevrolet'), ('Ford', 'Ford'), ('BMW', 'BMW'), ('Toyota', 'Toyota'), ('Audi', 'Audi'), ('Accura', 'Accura'), ('Volkswagen', 'Volkswagen'), ('Jeep', 'Jeep'), ('Mercedes', 'Mercedes'), ('Honda', 'Honda')], max_length=20, null=True)),
                ('vehicle_model', models.CharField(blank=True, choices=[('MDX', 'MDX'), ('RAM', 'RAM'), ('Wrangler', 'Wrangler'), ('Neon', 'Neon'), ('A3', 'A3'), ('Jetta', 'Jetta'), ('Passat', 'Passat'), ('A5', 'A5'), ('Legacy', 'Legacy'), ('Pathfinder', 'Pathfinder'), ('Malibu', 'Malibu'), ('92x', '92x'), ('Camry', 'Camry'), ('Forrestor', 'Forrestor'), ('95', '95'), ('E400', 'E400'), ('F150', 'F150'), ('Grand Cherokee', 'Grand Cherokee'), ('93', '93'), ('Maxima', 'Maxima'), ('Escape', 'Escape'), ('Tahoe', 'Tahoe'), ('Ultima', 'Ultima'), ('X5', 'X5'), ('Silverado', 'Silverado'), ('Civic', 'Civic'), ('Highlander', 'Highlander'), ('Fusion', 'Fusion'), ('Impreza', 'Impreza'), ('ML350', 'ML350'), ('Corolla', 'Corolla'), ('TL', 'TL'), ('CRV', 'CRV'), ('3 Series', '3 Series'), ('C300', 'C300'), ('X6', 'X6'), ('M5', 'M5'), ('Accord', 'Accord'), ('RSX', 'RSX')], max_length=20, null=True)),
                ('year_of_manufacture', models.IntegerField(blank=True, null=True)),
                ('acc_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='fraud.Account_holder')),
            ],
        ),
    ]
